from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminModeWindow(object):
    def setupUi(self, AdminModeWindow):
        AdminModeWindow.setObjectName("AdminModeWindow")
        AdminModeWindow.resize(1225, 836)
        font = QtGui.QFont()
        font.setPointSize(12)
        AdminModeWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(AdminModeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(390, 50, 831, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hall_make_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hall_make_button.setFont(font)
        self.hall_make_button.setObjectName("hall_make_button")
        self.horizontalLayout.addWidget(self.hall_make_button)
        self.session_make_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.session_make_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.session_make_button.setFont(font)
        self.session_make_button.setObjectName("session_make_button")
        self.horizontalLayout.addWidget(self.session_make_button)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 40, 1221, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(4, -1, 381, 41))
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(350, 0, 81, 781))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 765, 1221, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(390, 535, 821, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(650, 130, 311, 641))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(1110, 50, 221, 731))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 0, 221, 41))
        self.label_2.setObjectName("label_2")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 750, 1221, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(390, 500, 831, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(390, 700, 831, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.create_commercial_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.create_commercial_button.setObjectName("create_commercial_button")
        self.horizontalLayout_3.addWidget(self.create_commercial_button)
        self.create_feedback_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.create_feedback_button.setObjectName("create_feedback_button")
        self.horizontalLayout_3.addWidget(self.create_feedback_button)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 550, 271, 161))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(820, 550, 271, 161))
        self.label_6.setObjectName("label_6")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(0, 479, 961, 41))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(-28, 0, 61, 761))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 371, 41))
        self.label_7.setObjectName("label_7")
        self.sessions_table = QtWidgets.QTableWidget(self.centralwidget)
        self.sessions_table.setGeometry(QtCore.QRect(390, 130, 831, 371))
        self.sessions_table.setObjectName("sessions_table")
        self.sessions_table.setColumnCount(4)
        self.sessions_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sessions_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessions_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessions_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessions_table.setHorizontalHeaderItem(3, item)
        self.market_table = QtWidgets.QTableWidget(self.centralwidget)
        self.market_table.setGeometry(QtCore.QRect(0, 540, 391, 181))
        self.market_table.setObjectName("market_table")
        self.market_table.setColumnCount(3)
        self.market_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.market_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.market_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.market_table.setHorizontalHeaderItem(2, item)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 500, 391, 41))
        self.label_8.setObjectName("label_8")
        self.halls_table = QtWidgets.QTableWidget(self.centralwidget)
        self.halls_table.setGeometry(QtCore.QRect(0, 90, 391, 411))
        self.halls_table.setObjectName("halls_table")
        self.halls_table.setColumnCount(3)
        self.halls_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.halls_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.halls_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.halls_table.setHorizontalHeaderItem(2, item)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(390, 90, 831, 41))
        self.label_9.setObjectName("label_9")
        self.add_product_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_product_button.setGeometry(QtCore.QRect(90, 730, 201, 28))
        self.add_product_button.setObjectName("add_product_button")
        self.delete_session_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_session_button.setGeometry(QtCore.QRect(950, 10, 272, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_session_button.setFont(font)
        self.delete_session_button.setObjectName("delete_session_button")
        self.spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_box.setGeometry(QtCore.QRect(891, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spin_box.setFont(font)
        self.spin_box.setObjectName("spin_box")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(850, 10, 31, 31))
        self.label_10.setObjectName("label_10")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(280, 0, 93, 31))
        self.back_button.setObjectName("back_button")
        AdminModeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdminModeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1225, 26))
        self.menubar.setObjectName("menubar")
        AdminModeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdminModeWindow)
        self.statusbar.setObjectName("statusbar")
        AdminModeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AdminModeWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminModeWindow)

    def retranslateUi(self, AdminModeWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminModeWindow.setWindowTitle(_translate("AdminModeWindow", "MainWindow"))
        self.hall_make_button.setText(_translate("AdminModeWindow", "Зала"))
        self.session_make_button.setText(_translate("AdminModeWindow", "Сеанса"))
        self.label.setText(_translate("AdminModeWindow", "<html><head/><body><p>Добро пожаловать, <span style=\" font-weight:600;\">admin.</span></p></body></html>"))
        self.label_2.setText(_translate("AdminModeWindow", "<html><head/><body><p>Команды для создания:</p></body></html>"))
        self.label_4.setText(_translate("AdminModeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Реклама</span></p></body></html>"))
        self.label_3.setText(_translate("AdminModeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Отчёт</span></p></body></html>"))
        self.create_commercial_button.setText(_translate("AdminModeWindow", "Создать брошюру"))
        self.create_feedback_button.setText(_translate("AdminModeWindow", "Создать отчёт"))
        self.label_5.setText(_translate("AdminModeWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Создание персонализированой</span></p><p><span style=\" font-size:11pt;\">или неперсонализированой </span></p><p><span style=\" font-size:11pt;\">рекламной  брошюры.</span></p><p><span style=\" font-size:11pt;\">Создаёт файл в формате docx.</span></p></body></html>"))
        self.label_6.setText(_translate("AdminModeWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Создание подробного отчета</span></p><p><span style=\" font-size:11pt;\">на каждый зал кинотеатра.</span></p><p><span style=\" font-size:11pt;\">Создаёт презентацию в формате</span></p><p><span style=\" font-size:11pt;\">pptx.</span></p></body></html>"))
        self.label_7.setText(_translate("AdminModeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Залы и их занятость</span></p></body></html>"))
        item = self.sessions_table.horizontalHeaderItem(0)
        item.setText(_translate("AdminModeWindow", "Название"))
        item = self.sessions_table.horizontalHeaderItem(1)
        item.setText(_translate("AdminModeWindow", "Зал"))
        item = self.sessions_table.horizontalHeaderItem(2)
        item.setText(_translate("AdminModeWindow", "Цена"))
        item = self.sessions_table.horizontalHeaderItem(3)
        item.setText(_translate("AdminModeWindow", "Время"))
        item = self.market_table.horizontalHeaderItem(0)
        item.setText(_translate("AdminModeWindow", "Название"))
        item = self.market_table.horizontalHeaderItem(1)
        item.setText(_translate("AdminModeWindow", "Цена"))
        item = self.market_table.horizontalHeaderItem(2)
        item.setText(_translate("AdminModeWindow", "Количество"))
        self.label_8.setText(_translate("AdminModeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Список предметов в магазине:</span></p></body></html>"))
        item = self.halls_table.horizontalHeaderItem(0)
        item.setText(_translate("AdminModeWindow", "Название"))
        item = self.halls_table.horizontalHeaderItem(1)
        item.setText(_translate("AdminModeWindow", "Размер"))
        item = self.halls_table.horizontalHeaderItem(2)
        item.setText(_translate("AdminModeWindow", "Занятость"))
        self.label_9.setText(_translate("AdminModeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Информация о сеансах:</span></p></body></html>"))
        self.add_product_button.setText(_translate("AdminModeWindow", "Добавить товар"))
        self.delete_session_button.setText(_translate("AdminModeWindow", "Удалить сеанс"))
        self.label_10.setText(_translate("AdminModeWindow", "ID:"))
        self.back_button.setText(_translate("AdminModeWindow", "Выйти"))


class Ui_AuthorisationForm(object):
    def setupUi(self, AuthorisationForm):
        AuthorisationForm.setObjectName("AuthorisationForm")
        AuthorisationForm.resize(319, 382)
        AuthorisationForm.setMinimumSize(QtCore.QSize(319, 382))
        AuthorisationForm.setMaximumSize(QtCore.QSize(319, 382))
        font = QtGui.QFont()
        font.setPointSize(11)
        AuthorisationForm.setFont(font)
        self.confirm_button = QtWidgets.QPushButton(AuthorisationForm)
        self.confirm_button.setGeometry(QtCore.QRect(32, 227, 261, 31))
        self.confirm_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_button.setObjectName("confirm_button")
        self.out_label1 = QtWidgets.QLabel(AuthorisationForm)
        self.out_label1.setGeometry(QtCore.QRect(30, 20, 261, 41))
        self.out_label1.setObjectName("out_label1")
        self.formLayoutWidget = QtWidgets.QWidget(AuthorisationForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 133, 261, 82))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.give_login_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.give_login_label.setObjectName("give_login_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.give_login_label)
        self.give_password_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.give_password_label.setObjectName("give_password_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.give_password_label)
        self.enter_login = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.enter_login.setObjectName("enter_login")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.enter_login)
        self.enter_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.enter_password.setObjectName("enter_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.enter_password)
        self.wrong_label = QtWidgets.QLabel(AuthorisationForm)
        self.wrong_label.setGeometry(QtCore.QRect(30, 300, 261, 51))
        self.wrong_label.setObjectName("wrong_label")
        self.back_button = QtWidgets.QPushButton(AuthorisationForm)
        self.back_button.setGeometry(QtCore.QRect(0, 340, 101, 28))
        self.back_button.setObjectName("back_button")

        self.retranslateUi(AuthorisationForm)
        QtCore.QMetaObject.connectSlotsByName(AuthorisationForm)

    def retranslateUi(self, AuthorisationForm):
        _translate = QtCore.QCoreApplication.translate
        AuthorisationForm.setWindowTitle(_translate("AuthorisationForm", "Form"))
        self.confirm_button.setToolTip(_translate("AuthorisationForm", "<html><head/><body><p><span style=\" font-size:14pt;\">Кнопка</span></p></body></html>"))
        self.confirm_button.setWhatsThis(_translate("AuthorisationForm", "<html><head/><body><p><span style=\" font-size:14pt;\">Подтвердить</span></p></body></html>"))
        self.confirm_button.setText(_translate("AuthorisationForm", "Подтвердить"))
        self.out_label1.setText(_translate("AuthorisationForm", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Введите логин и пароль</span></p></body></html>"))
        self.give_login_label.setText(_translate("AuthorisationForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Логин:</span></p></body></html>"))
        self.give_password_label.setText(_translate("AuthorisationForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Пароль:</span></p></body></html>"))
        self.wrong_label.setText(_translate("AuthorisationForm", "<html><head/><body><p><br/></p></body></html>"))
        self.back_button.setText(_translate("AuthorisationForm", "Назад"))


class Ui_CreateCommercialWindow(object):
    def setupUi(self, CreateCommercialWindow):
        CreateCommercialWindow.setObjectName("CreateCommercialWindow")
        CreateCommercialWindow.resize(223, 128)
        CreateCommercialWindow.setMinimumSize(QtCore.QSize(223, 128))
        CreateCommercialWindow.setMaximumSize(QtCore.QSize(223, 128))
        self.combo_box = QtWidgets.QComboBox(CreateCommercialWindow)
        self.combo_box.setGeometry(QtCore.QRect(20, 30, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.combo_box.setFont(font)
        self.combo_box.setObjectName("combo_box")
        self.create_button = QtWidgets.QPushButton(CreateCommercialWindow)
        self.create_button.setGeometry(QtCore.QRect(20, 90, 181, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.create_button.setFont(font)
        self.create_button.setObjectName("create_button")

        self.retranslateUi(CreateCommercialWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateCommercialWindow)

    def retranslateUi(self, CreateCommercialWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateCommercialWindow.setWindowTitle(_translate("CreateCommercialWindow", "Form"))
        self.create_button.setText(_translate("CreateCommercialWindow", "Создать"))


class Ui_CreateHallWindow(object):
    def setupUi(self, CreateHallWindow):
        CreateHallWindow.setObjectName("CreateHallWindow")
        CreateHallWindow.resize(319, 382)
        CreateHallWindow.setMinimumSize(QtCore.QSize(319, 382))
        CreateHallWindow.setMaximumSize(QtCore.QSize(319, 382))
        font = QtGui.QFont()
        font.setPointSize(12)
        CreateHallWindow.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(CreateHallWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(44)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name_input.setObjectName("name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_input)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.width_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.width_input.setObjectName("width_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.width_input)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.length_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.length_input.setObjectName("length_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.length_input)
        self.error_widget = QtWidgets.QLabel(CreateHallWindow)
        self.error_widget.setGeometry(QtCore.QRect(10, 320, 301, 51))
        self.error_widget.setObjectName("error_widget")
        self.create_hall_button = QtWidgets.QPushButton(CreateHallWindow)
        self.create_hall_button.setGeometry(QtCore.QRect(60, 240, 201, 41))
        self.create_hall_button.setObjectName("create_hall_button")

        self.retranslateUi(CreateHallWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateHallWindow)

    def retranslateUi(self, CreateHallWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateHallWindow.setWindowTitle(_translate("CreateHallWindow", "Form"))
        self.label.setText(_translate("CreateHallWindow", "Название зала"))
        self.label_2.setText(_translate("CreateHallWindow", "Длина"))
        self.label_3.setText(_translate("CreateHallWindow", "Ширина"))
        self.error_widget.setText(_translate("CreateHallWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.create_hall_button.setText(_translate("CreateHallWindow", "Создать зал"))


class Ui_CreateProductWindow(object):
    def setupUi(self, CreateProductWindow):
        CreateProductWindow.setObjectName("CreateProductWindow")
        CreateProductWindow.resize(319, 382)
        CreateProductWindow.setMinimumSize(QtCore.QSize(319, 382))
        CreateProductWindow.setMaximumSize(QtCore.QSize(319, 382))
        font = QtGui.QFont()
        font.setPointSize(12)
        CreateProductWindow.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(CreateProductWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(44)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name_input.setObjectName("name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_input)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.price_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.price_input.setObjectName("price_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.price_input)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.anum_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.anum_input.setObjectName("anum_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.anum_input)
        self.create_product_button = QtWidgets.QPushButton(CreateProductWindow)
        self.create_product_button.setGeometry(QtCore.QRect(60, 240, 201, 41))
        self.create_product_button.setObjectName("create_product_button")
        self.error_widget = QtWidgets.QLabel(CreateProductWindow)
        self.error_widget.setGeometry(QtCore.QRect(10, 320, 301, 51))
        self.error_widget.setObjectName("error_widget")

        self.retranslateUi(CreateProductWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateProductWindow)

    def retranslateUi(self, CreateProductWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateProductWindow.setWindowTitle(_translate("CreateProductWindow", "Form"))
        self.label.setText(_translate("CreateProductWindow", "Название"))
        self.label_2.setText(_translate("CreateProductWindow", "Цена"))
        self.label_3.setText(_translate("CreateProductWindow", "Количество"))
        self.create_product_button.setText(_translate("CreateProductWindow", "Создать товар"))
        self.error_widget.setText(_translate("CreateProductWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))


class Ui_CreateSessionWindow(object):
    def setupUi(self, CreateSessionWindow):
        CreateSessionWindow.setObjectName("CreateSessionWindow")
        CreateSessionWindow.resize(319, 382)
        CreateSessionWindow.setMinimumSize(QtCore.QSize(319, 382))
        CreateSessionWindow.setMaximumSize(QtCore.QSize(319, 382))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        CreateSessionWindow.setFont(font)
        self.create_session_button = QtWidgets.QPushButton(CreateSessionWindow)
        self.create_session_button.setGeometry(QtCore.QRect(60, 240, 201, 31))
        self.create_session_button.setObjectName("create_session_button")
        self.formLayoutWidget = QtWidgets.QWidget(CreateSessionWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name_input.setObjectName("name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_input)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.date_edit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.date_edit.setObjectName("date_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.date_edit)
        self.time_edit = QtWidgets.QTimeEdit(self.formLayoutWidget)
        self.time_edit.setObjectName("time_edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.time_edit)
        self.spin_box = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spin_box.setObjectName("spin_box")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_box)
        self.combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.combo_box.setObjectName("combo_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_box)
        self.error_widget = QtWidgets.QLabel(CreateSessionWindow)
        self.error_widget.setGeometry(QtCore.QRect(10, 290, 301, 51))
        self.error_widget.setText("")
        self.error_widget.setObjectName("error_widget")

        self.retranslateUi(CreateSessionWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateSessionWindow)

    def retranslateUi(self, CreateSessionWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateSessionWindow.setWindowTitle(_translate("CreateSessionWindow", "Form"))
        self.create_session_button.setText(_translate("CreateSessionWindow", "Создать сеанс"))
        self.label.setText(_translate("CreateSessionWindow", "Название Фильма"))
        self.label_4.setText(_translate("CreateSessionWindow", "Зал"))
        self.label_5.setText(_translate("CreateSessionWindow", "Дата:(дд.мм.гггг)"))
        self.label_2.setText(_translate("CreateSessionWindow", "Цена"))
        self.label_3.setText(_translate("CreateSessionWindow", "Время (чч:мм)"))


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(319, 382)
        RegistrationWindow.setMinimumSize(QtCore.QSize(319, 382))
        RegistrationWindow.setMaximumSize(QtCore.QSize(319, 382))
        font = QtGui.QFont()
        font.setPointSize(11)
        RegistrationWindow.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(RegistrationWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 70, 395, 100))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.enter_login = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.enter_login.setObjectName("enter_login")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.enter_login)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.enter_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.enter_password.setObjectName("enter_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.enter_password)
        self.confirm_button = QtWidgets.QPushButton(RegistrationWindow)
        self.confirm_button.setGeometry(QtCore.QRect(70, 230, 171, 28))
        self.confirm_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_button.setObjectName("confirm_button")
        self.output_label = QtWidgets.QLabel(RegistrationWindow)
        self.output_label.setGeometry(QtCore.QRect(20, 290, 271, 41))
        self.output_label.setText("")
        self.output_label.setObjectName("output_label")
        self.back_button = QtWidgets.QPushButton(RegistrationWindow)
        self.back_button.setGeometry(QtCore.QRect(0, 340, 101, 28))
        self.back_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_button.setObjectName("back_button")

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "Form"))
        self.label.setText(_translate("RegistrationWindow", "Введите логин"))
        self.label_2.setText(_translate("RegistrationWindow", "Введите пароль"))
        self.confirm_button.setText(_translate("RegistrationWindow", "Подтвердить"))
        self.back_button.setText(_translate("RegistrationWindow", "Назад"))


class Ui_UserModeWindow(object):
    def setupUi(self, UserModeWindow):
        UserModeWindow.setObjectName("UserModeWindow")
        UserModeWindow.resize(1225, 836)
        UserModeWindow.setMinimumSize(QtCore.QSize(1225, 836))
        UserModeWindow.setMaximumSize(QtCore.QSize(1225, 836))
        font = QtGui.QFont()
        font.setPointSize(12)
        UserModeWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(UserModeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(10, 0, 261, 41))
        self.welcome_label.setObjectName("welcome_label")
        self.sessions_table = QtWidgets.QTableWidget(self.centralwidget)
        self.sessions_table.setGeometry(QtCore.QRect(0, 80, 841, 371))
        self.sessions_table.setObjectName("sessions_table")
        self.sessions_table.setColumnCount(0)
        self.sessions_table.setRowCount(0)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 40, 831, 41))
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 20, 1221, 51))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 435, 1221, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(830, 40, 21, 761))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.combo_box_1 = QtWidgets.QComboBox(self.centralwidget)
        self.combo_box_1.setGeometry(QtCore.QRect(890, 210, 291, 31))
        self.combo_box_1.setObjectName("combo_box_1")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 65, 1221, 31))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.buy_ticket_button = QtWidgets.QPushButton(self.centralwidget)
        self.buy_ticket_button.setGeometry(QtCore.QRect(930, 330, 221, 31))
        self.buy_ticket_button.setObjectName("buy_ticket_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(840, 50, 381, 31))
        self.label.setObjectName("label")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(395, 450, 31, 351))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 480, 841, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(-17, 40, 41, 761))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 450, 401, 41))
        self.label_2.setObjectName("label_2")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(0, 790, 1231, 21))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.buy_product_button = QtWidgets.QPushButton(self.centralwidget)
        self.buy_product_button.setGeometry(QtCore.QRect(100, 720, 221, 31))
        self.buy_product_button.setObjectName("buy_product_button")
        self.combo_box_2 = QtWidgets.QComboBox(self.centralwidget)
        self.combo_box_2.setGeometry(QtCore.QRect(60, 600, 291, 31))
        self.combo_box_2.setObjectName("combo_box_2")
        self.market_table = QtWidgets.QTableWidget(self.centralwidget)
        self.market_table.setGeometry(QtCore.QRect(410, 490, 431, 311))
        self.market_table.setObjectName("market_table")
        self.market_table.setColumnCount(0)
        self.market_table.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 450, 431, 41))
        self.label_3.setObjectName("label_3")
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(530, 7, 241, 31))
        self.update_button.setObjectName("update_button")
        self.ticket_wrong_label = QtWidgets.QLabel(self.centralwidget)
        self.ticket_wrong_label.setGeometry(QtCore.QRect(840, 400, 381, 41))
        self.ticket_wrong_label.setObjectName("ticket_wrong_label")
        self.market_wrong_label = QtWidgets.QLabel(self.centralwidget)
        self.market_wrong_label.setGeometry(QtCore.QRect(10, 755, 401, 41))
        self.market_wrong_label.setText("")
        self.market_wrong_label.setObjectName("market_wrong_label")
        self.input_val = QtWidgets.QLineEdit(self.centralwidget)
        self.input_val.setGeometry(QtCore.QRect(210, 640, 141, 31))
        self.input_val.setObjectName("input_val")
        self.input_tick = QtWidgets.QLineEdit(self.centralwidget)
        self.input_tick.setGeometry(QtCore.QRect(1040, 250, 141, 31))
        self.input_tick.setObjectName("input_tick")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(850, 500, 371, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(890, 250, 151, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 640, 151, 31))
        self.label_6.setObjectName("label_6")
        self.photo_label = QtWidgets.QLabel(self.centralwidget)
        self.photo_label.setGeometry(QtCore.QRect(850, 540, 371, 241))
        self.photo_label.setText("")
        self.photo_label.setObjectName("photo_label")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(380, 10, 93, 28))
        self.back_button.setObjectName("back_button")
        UserModeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(UserModeWindow)
        self.statusbar.setObjectName("statusbar")
        UserModeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(UserModeWindow)
        QtCore.QMetaObject.connectSlotsByName(UserModeWindow)

    def retranslateUi(self, UserModeWindow):
        _translate = QtCore.QCoreApplication.translate
        UserModeWindow.setWindowTitle(_translate("UserModeWindow", "MainWindow"))
        self.welcome_label.setText(_translate("UserModeWindow", "<html><head/><body><p>Добро пожаловать, <span style=\" font-weight:600;\">.</span></p></body></html>"))
        self.label_9.setText(_translate("UserModeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Информация о сеансах:</span></p></body></html>"))
        self.buy_ticket_button.setText(_translate("UserModeWindow", "Купить"))
        self.label.setText(_translate("UserModeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Купить билет</span></p></body></html>"))
        self.label_2.setText(_translate("UserModeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Купить предмет в магазине.</span></p></body></html>"))
        self.buy_product_button.setText(_translate("UserModeWindow", "Купить"))
        self.label_3.setText(_translate("UserModeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Информация о магазине:</span></p></body></html>"))
        self.update_button.setText(_translate("UserModeWindow", "Обновить"))
        self.ticket_wrong_label.setText(_translate("UserModeWindow", "<html><head/><body><p><br/></p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("UserModeWindow", "Спасибо за использование приложения!"))
        self.label_5.setText(_translate("UserModeWindow", "Введите кол-во:"))
        self.label_6.setText(_translate("UserModeWindow", "Введите кол-во:"))
        self.back_button.setText(_translate("UserModeWindow", "Выйти"))


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(319, 382)
        StartWindow.setMinimumSize(QtCore.QSize(319, 382))
        StartWindow.setMaximumSize(QtCore.QSize(319, 382))
        font = QtGui.QFont()
        font.setPointSize(11)
        StartWindow.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(StartWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 210, 241, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.log_in_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.log_in_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.log_in_button.setObjectName("log_in_button")
        self.verticalLayout.addWidget(self.log_in_button)
        self.registration_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.registration_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registration_button.setObjectName("registration_button")
        self.verticalLayout.addWidget(self.registration_button)
        self.output_label = QtWidgets.QLabel(StartWindow)
        self.output_label.setGeometry(QtCore.QRect(80, 10, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.output_label.setFont(font)
        self.output_label.setObjectName("output_label")
        self.photo_label = QtWidgets.QLabel(StartWindow)
        self.photo_label.setGeometry(QtCore.QRect(80, 80, 171, 111))
        self.photo_label.setText("")
        self.photo_label.setObjectName("photo_label")

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "Form"))
        self.log_in_button.setText(_translate("StartWindow", "Войти"))
        self.registration_button.setText(_translate("StartWindow", "Зарегистрироваться"))
        self.output_label.setText(_translate("StartWindow", "<html><head/><body><p>Добро пожаловать в</p><p>систему кинотеатра!</p></body></html>"))
