# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthorisationForm(object):
    def setupUi(self, AuthorisationForm):
        AuthorisationForm.setObjectName("AuthorisationForm")
        AuthorisationForm.resize(319, 382)
        AuthorisationForm.setMinimumSize(QtCore.QSize(319, 382))
        AuthorisationForm.setMaximumSize(QtCore.QSize(319, 382))
        font = QtGui.QFont()
        font.setPointSize(11)
        AuthorisationForm.setFont(font)
        self.confirm_button = QtWidgets.QPushButton(AuthorisationForm)
        self.confirm_button.setGeometry(QtCore.QRect(32, 227, 261, 31))
        self.confirm_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_button.setObjectName("confirm_button")
        self.out_label1 = QtWidgets.QLabel(AuthorisationForm)
        self.out_label1.setGeometry(QtCore.QRect(30, 20, 261, 41))
        self.out_label1.setObjectName("out_label1")
        self.formLayoutWidget = QtWidgets.QWidget(AuthorisationForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 133, 261, 82))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.give_login_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.give_login_label.setObjectName("give_login_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.give_login_label)
        self.give_password_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.give_password_label.setObjectName("give_password_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.give_password_label)
        self.enter_login = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.enter_login.setObjectName("enter_login")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.enter_login)
        self.enter_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.enter_password.setObjectName("enter_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.enter_password)
        self.wrong_label = QtWidgets.QLabel(AuthorisationForm)
        self.wrong_label.setGeometry(QtCore.QRect(30, 300, 261, 51))
        self.wrong_label.setObjectName("wrong_label")
        self.back_button = QtWidgets.QPushButton(AuthorisationForm)
        self.back_button.setGeometry(QtCore.QRect(0, 340, 101, 28))
        self.back_button.setObjectName("back_button")

        self.retranslateUi(AuthorisationForm)
        QtCore.QMetaObject.connectSlotsByName(AuthorisationForm)

    def retranslateUi(self, AuthorisationForm):
        _translate = QtCore.QCoreApplication.translate
        AuthorisationForm.setWindowTitle(_translate("AuthorisationForm", "Form"))
        self.confirm_button.setToolTip(_translate("AuthorisationForm", "<html><head/><body><p><span style=\" font-size:14pt;\">Кнопка</span></p></body></html>"))
        self.confirm_button.setWhatsThis(_translate("AuthorisationForm", "<html><head/><body><p><span style=\" font-size:14pt;\">Подтвердить</span></p></body></html>"))
        self.confirm_button.setText(_translate("AuthorisationForm", "Подтвердить"))
        self.out_label1.setText(_translate("AuthorisationForm", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Введите логин и пароль</span></p></body></html>"))
        self.give_login_label.setText(_translate("AuthorisationForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Логин:</span></p></body></html>"))
        self.give_password_label.setText(_translate("AuthorisationForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Пароль:</span></p></body></html>"))
        self.wrong_label.setText(_translate("AuthorisationForm", "<html><head/><body><p><br/></p></body></html>"))
        self.back_button.setText(_translate("AuthorisationForm", "Назад"))
