# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_create_hall.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateHallWindow(object):
    def setupUi(self, CreateHallWindow):
        CreateHallWindow.setObjectName("CreateHallWindow")
        CreateHallWindow.resize(319, 382)
        CreateHallWindow.setMinimumSize(QtCore.QSize(319, 382))
        CreateHallWindow.setMaximumSize(QtCore.QSize(319, 382))
        font = QtGui.QFont()
        font.setPointSize(12)
        CreateHallWindow.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(CreateHallWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(44)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name_input.setObjectName("name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_input)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.width_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.width_input.setObjectName("width_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.width_input)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.length_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.length_input.setObjectName("length_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.length_input)
        self.error_widget = QtWidgets.QLabel(CreateHallWindow)
        self.error_widget.setGeometry(QtCore.QRect(10, 320, 301, 51))
        self.error_widget.setObjectName("error_widget")
        self.create_hall_button = QtWidgets.QPushButton(CreateHallWindow)
        self.create_hall_button.setGeometry(QtCore.QRect(60, 240, 201, 41))
        self.create_hall_button.setObjectName("create_hall_button")

        self.retranslateUi(CreateHallWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateHallWindow)

    def retranslateUi(self, CreateHallWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateHallWindow.setWindowTitle(_translate("CreateHallWindow", "Form"))
        self.label.setText(_translate("CreateHallWindow", "Название зала"))
        self.label_2.setText(_translate("CreateHallWindow", "Длина"))
        self.label_3.setText(_translate("CreateHallWindow", "Ширина"))
        self.error_widget.setText(_translate("CreateHallWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.create_hall_button.setText(_translate("CreateHallWindow", "Создать зал"))
