# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_create_session.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateSessionWindow(object):
    def setupUi(self, CreateSessionWindow):
        CreateSessionWindow.setObjectName("CreateSessionWindow")
        CreateSessionWindow.resize(319, 382)
        CreateSessionWindow.setMinimumSize(QtCore.QSize(319, 382))
        CreateSessionWindow.setMaximumSize(QtCore.QSize(319, 382))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        CreateSessionWindow.setFont(font)
        self.create_session_button = QtWidgets.QPushButton(CreateSessionWindow)
        self.create_session_button.setGeometry(QtCore.QRect(60, 240, 201, 31))
        self.create_session_button.setObjectName("create_session_button")
        self.formLayoutWidget = QtWidgets.QWidget(CreateSessionWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name_input.setObjectName("name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_input)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.date_edit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.date_edit.setObjectName("date_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.date_edit)
        self.time_edit = QtWidgets.QTimeEdit(self.formLayoutWidget)
        self.time_edit.setObjectName("time_edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.time_edit)
        self.spin_box = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spin_box.setObjectName("spin_box")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_box)
        self.combo_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.combo_box.setObjectName("combo_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_box)
        self.error_widget = QtWidgets.QLabel(CreateSessionWindow)
        self.error_widget.setGeometry(QtCore.QRect(10, 290, 301, 51))
        self.error_widget.setText("")
        self.error_widget.setObjectName("error_widget")

        self.retranslateUi(CreateSessionWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateSessionWindow)

    def retranslateUi(self, CreateSessionWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateSessionWindow.setWindowTitle(_translate("CreateSessionWindow", "Form"))
        self.create_session_button.setText(_translate("CreateSessionWindow", "Создать сеанс"))
        self.label.setText(_translate("CreateSessionWindow", "Название Фильма"))
        self.label_4.setText(_translate("CreateSessionWindow", "Зал"))
        self.label_5.setText(_translate("CreateSessionWindow", "Дата:(дд.мм.гггг)"))
        self.label_2.setText(_translate("CreateSessionWindow", "Цена"))
        self.label_3.setText(_translate("CreateSessionWindow", "Время (чч:мм)"))
