# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(319, 382)
        RegistrationWindow.setMinimumSize(QtCore.QSize(319, 382))
        RegistrationWindow.setMaximumSize(QtCore.QSize(319, 382))
        font = QtGui.QFont()
        font.setPointSize(11)
        RegistrationWindow.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(RegistrationWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 70, 395, 100))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.enter_login = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.enter_login.setObjectName("enter_login")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.enter_login)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.enter_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.enter_password.setObjectName("enter_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.enter_password)
        self.confirm_button = QtWidgets.QPushButton(RegistrationWindow)
        self.confirm_button.setGeometry(QtCore.QRect(70, 230, 171, 28))
        self.confirm_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_button.setObjectName("confirm_button")
        self.output_label = QtWidgets.QLabel(RegistrationWindow)
        self.output_label.setGeometry(QtCore.QRect(20, 290, 271, 41))
        self.output_label.setText("")
        self.output_label.setObjectName("output_label")
        self.back_button = QtWidgets.QPushButton(RegistrationWindow)
        self.back_button.setGeometry(QtCore.QRect(0, 340, 101, 28))
        self.back_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_button.setObjectName("back_button")

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "Form"))
        self.label.setText(_translate("RegistrationWindow", "Введите логин"))
        self.label_2.setText(_translate("RegistrationWindow", "Введите пароль"))
        self.confirm_button.setText(_translate("RegistrationWindow", "Подтвердить"))
        self.back_button.setText(_translate("RegistrationWindow", "Назад"))
