# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_start.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(319, 382)
        StartWindow.setMinimumSize(QtCore.QSize(319, 382))
        StartWindow.setMaximumSize(QtCore.QSize(319, 382))
        font = QtGui.QFont()
        font.setPointSize(11)
        StartWindow.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(StartWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 210, 241, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.log_in_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.log_in_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.log_in_button.setObjectName("log_in_button")
        self.verticalLayout.addWidget(self.log_in_button)
        self.registration_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.registration_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registration_button.setObjectName("registration_button")
        self.verticalLayout.addWidget(self.registration_button)
        self.output_label = QtWidgets.QLabel(StartWindow)
        self.output_label.setGeometry(QtCore.QRect(80, 10, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.output_label.setFont(font)
        self.output_label.setObjectName("output_label")
        self.photo_label = QtWidgets.QLabel(StartWindow)
        self.photo_label.setGeometry(QtCore.QRect(80, 80, 171, 111))
        self.photo_label.setText("")
        self.photo_label.setObjectName("photo_label")

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "Form"))
        self.log_in_button.setText(_translate("StartWindow", "Войти"))
        self.registration_button.setText(_translate("StartWindow", "Зарегистрироваться"))
        self.output_label.setText(_translate("StartWindow", "<html><head/><body><p>Добро пожаловать в</p><p>систему кинотеатра!</p></body></html>"))
